### ISSUE TITLE
Port a english version

### ISSUE THREAD

**Issue by YanLobianchi** [bilibili-helper/bilibili-helper#630]
### Purpose of the issue
- [ ]  Bug report (encountered problems/errors)
- [x]  Feature request (request for new functionality)
- [ ]  Question

### Description of the issue
Browser: all
Feature: english language version option

**Comment by zacyu** [comment]
Hey Yan! Can you please clarify on what you are expecting from the English port? Since our extension only adds additional functionalities to bilibili.com, which itself is only available in Simplified Chinese at this moment, I am not sure if i18n for only the extension would help much.

I would like to note that the pop-out menu and notification texts are currently available in English. The preference page and the injected tooltip are not translated yet.

**Comment by jjj201200** [comment]
@zacyu 人家已经写了是设置页面嘛233，我有空去完善一下，然后1.2.2不久就上架吧应该

**Comment by jjj201200** [comment]
we have support it in v1.2.6
